---
title: "Happy New Year"
author: aravindavk
description: "2021 was a great year for us with a handful of projects related to GlusterFS feature development, training, and other Open-source projects. We are excited about 2022 with many projects in the pipeline."
---

== 2021: Year in review

2021 was a great year for us with a handful of projects related to GlusterFS feature development, training, and other Open-source projects.

The following are the highlights of the year 2021:

=== Persistent Storage for applications running on Kubernetes

We made 12 feature rich releases in 2021. We are very happy to learn that many users are liking the project and have started using it in their production deployments. This project has gained  more than 25 contributors and close to 400 Github stars in 2021.

=== New team member

https://twitter.com/vatsa287[Shreevatsa] has joined Kadalu. He started working with Kadalu as an intern and now he is working full time. This year you all can expect more contributions from him to Kadalu and GlusterFS.

=== GlusterFS Administration Training

We conducted a  tailor-made training program to upskill a few admins. The training was more focused on configuring GlusterFS volumes to suit their business needs.

=== GlusterFS feature development

In 2021 we have successfully completed a few projects that enhanced the functionality of GlusterFS.

=== Test framework updates

Binnacle is the home grown test framework that we use to test the Kadalu projects. It is a generic framework that can be used for testing other projects as well. Binnacle allows the test case authors to focus on the domain rather than spending time on solving programming language quirks.

Further information on Kadalu Binnacle can be found https://kadalu.io/docs/binnacle/main/quick-start/[here].

== 2022

Happy new year to all!

We are excited about 2022 with many projects in the pipeline.

=== GlusterFS Community

Kadalu.io is one of the active contributors in the GlusterFS community. We continue to work on the fixes and features that will improve the filesystem experience.

=== GlusterFS feature development

We can design, prototype and implement GlusterFS/Kadalu Storage tools, applications and features for your Company. Get a competitive advantage by using the features specially customized to your company/users needs. We will also help to submit the features to the Gluster upstream project(GlusterFS is licensed under GPL-v3).

=== Leela Gangavarapu joins Kadalu Kubernetes integration core team

https://www.linkedin.com/in/leelavg[Leela] has been contributing to Kadalu Kubernetes integration projects for a long time. He is very active and is helping the Kadalu project in numerous ways.

=== Kadalu Kubernetes Storage

With many releases in the last year, we are focused on releasing the 1.0 version this year.

=== New Project announcement - Kadalu Storage

Kadalu Storage is a modern distributed Storage solution with the focus of providing scalable, easy-to-use Volumes for the Cloud, On-premise, or Raspberry Pis.

Kadalu Storage uses the core filesystem layer from GlusterFS and builds the new ecosystem from the ground up. The modern storage manager helps to manage multiple storage pools effectively and provides ReST APIs to integrate with other applications.

We will write about this project in detail in our next blog post.

=== Automated Testing

We are a small company focused on creating production-ready storage solutions. We are heavily invested in automated testing, adding tests with the Binnacle test framework is always fun. We also adopted containerized testing to test all the functionalities, upgrade tests and workloads. All performance tests will use VM or physical nodes.

=== Community meeting

We will start a Kadalu Storage community meeting once every month. In the meeting we can discuss new features, blocker issues or feature ideas.

Follow us on https://twitter.com/kadaluio[Twitter/kadaluio] to know more about the community meetings, new features and other updates.
