= About Us

== Kadalu Storage

Kadalu Storage is opinionated distribution of GlusterFS. Kadalu Storage brings good parts of GlusterFS with added enhancements like improved Quota, Management layer and others.

Kadalu Storage project offers a lightweight Persistent storage solution for applications running in Kubernetes. It provides operator, which spawns CSI drivers, and also storage exporter based on the configuration provided. Kadalu Storage natively integrates with Kubernetes apis to provide the efficient solution without the need of Glusterd.

For Standalone use cases, Kadalu Storage provides external Control plane for managing multiple Clusters easily.


== Company

Kadalu Software Private Limited is incorporated in 2019 by the core team members of GlusterFS with the focus of providing easy, scalable Storage solution for Kubernetes and for Standalone use cases.

== Team

++++
<div class="grid grid-cols-4">
    <div class="">
         <div style="width:200px;height:250px" class="bg-gray-200">
         </div>
         <strong>Amar Tumballi</strong>
    </div>
    <div class="">
         <div style="width:200px;height:250px" class="bg-gray-200">
         </div>
         <strong>Aravinda Vishwanathapura</strong>
    </div>
    <div class="">
         <div style="width:200px;height:250px" class="bg-gray-200">
         </div>
         <strong>Sachidanda Urs</strong>
    </div>
    <div class="">
         <div style="width:200px;height:250px" class="bg-gray-200">
         </div>
         <strong>Pallavi</strong>
    </div>
</div>
++++

== Advisory Group

++++
<div class="grid grid-cols-3">
    <div class="">
         <div style="width:200px;height:250px" class="bg-gray-200">
         </div>
         <strong>Satish Mohan</strong>
    </div>
    <div class="">
         <div style="width:200px;height:250px" class="bg-gray-200">
         </div>
         <strong>Sankarshan</strong>
    </div>
</div>
++++
