---
title: About Us
---

== Kadalu Storage

Kadalu Storage is an opinionated distribution of GlusterFS. Kadalu Storage brings good parts of GlusterFS with added enhancements like improved Quota, Management layer and others.

Kadalu Storage project offers a lightweight Persistent storage solution for applications running in Kubernetes. It provides an operator, which spawns CSI drivers, and also a storage exporter based on the configuration provided. Kadalu Storage natively integrates with Kubernetes APIs to provide an efficient solution without the need for Glusterd.

For Standalone use cases, Kadalu Storage provides an external control plane for managing multiple Clusters easily.


== Company

Kadalu Software Private Limited is incorporated in 2019 by the core team members of GlusterFS with the focus of providing an easy, scalable Storage solution for Kubernetes and for Standalone use cases.

// == Team

// ++++
// <div class="grid grid-cols-4">
//     <div class="">
//          <div style="width:200px;height:250px" class="bg-gray-200">
//          </div>
//          <strong>Amar Tumballi</strong>
//     </div>
//     <div class="">
//          <div style="width:200px;height:250px" class="bg-gray-200">
//          </div>
//          <strong>Aravinda Vishwanathapura</strong>
//     </div>
//     <div class="">
//          <div style="width:200px;height:250px" class="bg-gray-200">
//          </div>
//          <strong>Sachidanda Urs</strong>
//     </div>
//     <div class="">
//          <div style="width:200px;height:250px" class="bg-gray-200">
//          </div>
//          <strong>Pallavi</strong>
//     </div>
// </div>
// ++++

// == Advisory Group

// ++++
// <div class="grid grid-cols-3">
//     <div class="">
//          <div style="width:200px;height:250px" class="bg-gray-200">
//          </div>
//          <strong>Satish Mohan</strong>
//     </div>
//     <div class="">
//          <div style="width:200px;height:250px" class="bg-gray-200">
//          </div>
//          <strong>Sankarshan</strong>
//     </div>
// </div>
// ++++
